# Generated by Django 4.1.7 on 2023-03-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of this type of Activity', max_length=30)),
                ('description', models.CharField(help_text='The description of the Activity', max_length=150)),
                ('player', models.CharField(default='', help_text='Name of player currently working', max_length=30)),
                ('date_started', models.DateField()),
                ('days', models.IntegerField(default=7)),
                ('days_completed', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False, help_text='Can all players see this activity?')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this type of Player', max_length=30)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
